name: Create GitHub Release on Tag

on:
  push:
    tags:
      - 'v[0-9]+.0.0'  # matches only like v1.0.0, v2.0.0

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release