name: Create GitHub Release on Major Tag

on:
  push:
    tags:
      - "v[0-9]*.0.0" # triggers only for v1.0.0, v2.0.0, v10.0.0, ...

# REQUIRED so the job can create a Release
permissions:
  contents: write

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    # extra guard (only *.0.0 tags)
    if: startsWith(github.ref, 'refs/tags/') && endsWith(github.ref_name, '.0.0')
    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug refs (optional)
        run: |
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }} # requires repo setting: Actions → Workflow permissions → Read and write
